[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "phamos"
authors = [
    { name = "Phamos GmbH", email = "support@phamos.eu" }
]
description = "ERPNext Enhancement for Phamos.eu"
requires-python = ">=3.10,<3.14"
readme = "README.md"
dynamic = ["version"]
dependencies = [
    "icalendar==6.1.1",
]

[project.urls]
Homepage = "https://github.com/phamos-eu/phamos"